name: Grupo 7

on:
  push:
    branches: [ "main", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VARIABLE_UNO: "Sistemas"
      VARIABLE_DOS: "UTP"
      VARIABLE_TRES: "Activo"

    steps:
      - name: Inicializar archivo JSON
        run: |
          echo "{" > resultado.json
          echo "  \"grupo\": \"Grupo 7\"," >> resultado.json
      - name: Prueba de mensajes
        run: |
          echo "Hola Grupo 7, bienvenidos al workflow de automatización."
          echo "  \"saludo\": \"Hola Grupo 7, bienvenidos al workflow de automatización.\"," >> resultado.json
      - name: Variables creada en el workflow
        run: |
          echo "Var 1: ${{ env.VARIABLE_UNO }}"
          echo "Var 2: ${{ env.VARIABLE_DOS }}"
          echo "Var 3: ${{ env.VARIABLE_TRES }}"
          echo "  \"variables_env\": {" >> resultado.json
          echo "    \"var1\": \"${{ env.VARIABLE_UNO }}\"," >> resultado.json
          echo "    \"var2\": \"${{ env.VARIABLE_DOS }}\"," >> resultado.json
          echo "    \"var3\": \"${{ env.VARIABLE_TRES }}\"" >> resultado.json
          echo "  }," >> resultado.json
      - name: Variables del entorno del Github Actions
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Dueño/Actor: ${{ github.actor }}"
          echo "ID del Run: ${{ github.run_id }}"
          echo "  \"variables_github\": {" >> resultado.json
          echo "    \"repositorio\": \"${{ github.repository }}\"," >> resultado.json
          echo "    \"dueno\": \"${{ github.actor }}\"," >> resultado.json
          echo "    \"run_id\": \"${{ github.run_id }}\"" >> resultado.json
          echo "  }," >> resultado.json

      - name: Con Despedida
        if: ${{ env.VARIABLE_TRES == 'Activo' }}
        run: |
          echo "¡Hasta luego Grupo 7! Gracias por usar GitHub Actions."
          echo "  \"despedida\": \"¡Hasta luego Grupo 7! Gracias por usar GitHub Actions.\"" >> resultado.json
          echo "}" >> resultado.json

      - name: Sin despedida
        if: ${{ env.VARIABLE_TRES == 'Inactivo' }}
        run: |
          echo "Este mensaje no se leerá ni se guardará."

      - name: Mostrar resultado JSON plano
        run: cat resultado.json
