name: Grupo 7

on:
  push:
    branches:
      - main

env:
  GRUPO: "Grupo 7"
  MENSAJE: "Hola a todos desde el workflow"
  MOSTRAR_DESPEDIDA: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Prueba de mensajes
        run: |
          echo "Saludo para el ${GRUPO}"
          echo "${MENSAJE}"

      - name: Variables creada en el workflow
        run: |
          echo "Variable GRUPO: ${GRUPO}"
          echo "Variable MENSAJE: ${MENSAJE}"
          echo "Variable MOSTRAR_DESPEDIDA: ${MOSTRAR_DESPEDIDA}"

      - name: Variables del entorno del Github Actions
        run: |
          echo "Repositorio (GITHUB_REPOSITORY): ${GITHUB_REPOSITORY}"
          echo "Actor (GITHUB_ACTOR): ${GITHUB_ACTOR}"
          echo "Workflow (GITHUB_WORKFLOW): ${GITHUB_WORKFLOW}"

      - name: Con Despedida
        if: ${{ env.MOSTRAR_DESPEDIDA == 'true' }}
        run: |
          echo "Despedida para el ${GRUPO}: ¡Hasta luego!"

      - name: Sin despedida
        if: ${{ env.MOSTRAR_DESPEDIDA == 'false' }}
        run: |
          echo "Este mensaje no debería mostrarse porque MOSTRAR_DESPEDIDA es true."

      - name: Crear archivo JSON con resultados
        run: |
          cat << 'EOF' > resultado_grupo7.json
          {
            "grupo": "${GRUPO}",
            "mensaje": "${MENSAJE}",
            "mostrar_despedida": "${MOSTRAR_DESPEDIDA}",
            "github_repository": "${GITHUB_REPOSITORY}",
            "github_actor": "${GITHUB_ACTOR}",
            "github_workflow": "${GITHUB_WORKFLOW}"
          }
          EOF

      - name: Subir JSON como artifact
        uses: actions/upload-artifact@v4
        with:
          name: resultado-grupo7
          path: resultado_grupo7.json
